export const
  POSTS_RECEIVED = 'POSTS_RECEIVED',
  POSTS_LIST_VOTE_SUCCESS = 'POSTS_LIST_VOTE_SUCCESS',
  SET_SELECTED_POST = 'SET_SELECTED_POST',
  CATEGORIES_RECEIVED = 'CATEGORIES_RECEIVED',
  POST_DETAIL_RECEIVED = 'POST_DETAIL_RECEIVED',
  POST_VOTE_SUCCESS = 'POST_VOTE_SUCCESS',
  POST_COMMENTS_RECEIVED = 'POST_COMMENTS_RECEIVED',
  DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS',
  CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS',
  UPDATE_COMMENT_SUCCESS = 'UPDATE_COMMENT_SUCCESS';